apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubecost
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: kubecost
  releaseName: kubecost
  interval: 5m
  chart:
    spec:
      chart: cost-analyzer
      version: "1.107.0"  # Replace with latest stable version
      sourceRef:
        kind: HelmRepository
        name: kubecost
        namespace: flux-system
  values:
    kubecostProductConfigs:
      clusterName: "project-vpc"  # Use your actual EKS cluster name
      cloudIntegration:
        enabled: true
        aws:
          enabled: true
          useServiceAccount: true
          curEnabled: true
    global:
      grafana:
        enabled: true
      prometheus:
        enabled: true
        kubeStateMetrics:
          enabled: true
    serviceAccount:
      create: false
      name: kubecost-irsa