# karpenter-helmrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: karpenter
  namespace: flux-system
spec:
  type: oci
  interval: 10m
  url: oci://public.ecr.aws/karpenter