apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  values:
    installCRDs: true
    settings:
      clusterName: "project-vpc"
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::361769572081:role/KarpenterControllerRole-project-vpc"
    controller:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
    webhook:
      enabled: true
    controllerPort:
      httpMetricsPortname: "http-metrics-port"
      httpsWebhookPortname: "https-webhook-port"
